name: deploy-beta

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: dim.rsa # optional
        known_hosts: ${{ secrets.REMOTE_HOST }}
    - uses: actions/checkout@v2
    - name: Cache .yarn
      uses: c-hive/gha-yarn-cache@v1
    - name: Cache node_modules
      uses: actions/cache@v2
      env:
        cache-name: cache_node_modules
      with:
        path: $GITHUB_WORKSPACE/node_modules
        key: node_modules-${{ hashFiles('**/yarn.lock')}}
        restore-keys: |
          node_modules-
    - name: Cache .cache
      uses: actions/cache@v2
      env:
        cache-name: cache_home_cache
      with:
        path: $HOME/.cache/
        key: home-cache-${{ hashFiles('**/yarn.lock')}}
        restore-keys: |
          home-cache-
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn run lint-check
    - name: Build and deploy
      run: ./build/ga_build.sh

